version: "3.9"

services:
    db:
        image: mongo:4.4-focal
        volumes:
            - database:/data/db
        ports:
            - "27017:27017"
        networks:
            - kodebi-network
    api:
        env_file:
            - ./.env
        build:
            context: ./
            target: "dev"
        depends_on:
            - db
        volumes:
            - ./:/root/api:cached
        ports:
            - "4000:4000"
        networks:
            - kodebi-network
networks:
    kodebi-network:
        driver: bridge
volumes:
    database:
        driver: local
